services:
    xfce:
        public: true
        privileged: true
        container_name: go
        image: accetto/ubuntu-vnc-xfce:latest
        ports:
            - 5901:5901
            - 6901:6901
        volumes:
            - /home/headless/Documents/
            - /home/headless/Desktop/
            - /home/headless/Downloads/
        resources:
          cpu: 2000m
          memory: 6Gi
          storage:
            size: 10Gi
            class: standard
